### ISSUE TITLE
Invalid Chai property: eventually

### ISSUE THREAD

**Issue by moshthepitt** [saber-hq/saber-common#483]
How do I fix `Invalid Chai property: eventually` when running tests using chai-solana?  Anyone experienced this before?

**Comment by macalinao** [comment]
Use Chai 4.3.4 or below. They introduced a breaking change.

**Comment by macalinao** [comment]
added some docs for this here: https://github.com/saber-hq/saber-common/commit/4015d5a18ecef355ed747e2e29f104177c88bbc1

hopefully google picks this up

**Comment by moshthepitt** [comment]
Thanks @macalinao - much appreciated!
