### ISSUE TITLE
How do I get a list of `swapAccount`s?

### ISSUE THREAD

**Issue by drinksbydrew** [saber-hq/saber-common#487]
The stableswap-sdk [code](https://github.com/saber-hq/saber-common/blob/c18e57b011e868fcc266c52f99e38eec1c895fb1/packages/stableswap-sdk/src/instructions/common.ts#L23) describes the `swapAccount` parameter as "The public key identifying this instance of the Stable Swap."

Where can I find a mapping of pool pairs to swapAccount public keys? (i.e. how do I find what `swapAccount` to pass into methods like `loadExchangeInfoFromSwapAccount`?)

should I just call `getProgramAccounts` passing in the `SWAP_PROGRAM_ID`? e.g.

```
curl https://api.mainnet-beta.solana.com -X POST -H "Content-Type: application/json" -d '
  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getProgramAccounts",
    "params": [
      "SSwpkEEcbUqx4vtoEByFjSkhKdCT862DNVb52nZg1UZ",
      {
        "encoding": "base64"
      }
    ]
  }
'
```

**Comment by ebramanti** [comment]
This might be what you are looking for: https://github.com/saber-hq/saber-registry-dist

Saber also maintains this list in a public API here: https://registry.saber.so/data/pools-info.mainnet.json

**Comment by macalinao** [comment]
Thanks for the answer @ebramanti 

Use the registry
