### ISSUE TITLE
Add Solscan explorer link

### ISSUE THREAD

**Issue by haodev007** [saber-hq/saber-common#663]
Hi

solana-contrib is now just providing solana explorer link.
Can we add solscan link?

```typescript
 generateSolanaExplorerLink(cluster: Cluster = "mainnet-beta"): string {
    return `https://explorer.solana.com/tx/${this.signature}?cluster=${cluster}`;
  }
```

**Comment by haodev007** [comment]
resolved by PR #664

**Comment by haodev007** [comment]
Hi @michaelhly 
Do you know when it will be published?

**Comment by michaelhly** [comment]
Publishing now ..

**Comment by haodev007** [comment]
Hi, I think we need to add generateTXLink() in not only `TransactionReceipt` but also `PendingTransaction` 
It will be solscan link for pending transaction.

**Comment by michaelhly** [comment]
Feel free to submit another PR

**Comment by haodev007** [comment]
> Feel free to submit another PR

Added generateTXLink() in `PendingTransaction` by this PR #675
