### ISSUE TITLE
Walletconnect support

### ISSUE THREAD

**Issue by jeffhu1** [saber-hq/saber-common#699]
Hi Ian, do you know if it's possible to get walletconnect support? It seems like [adapter](https://github.com/solana-labs/wallet-adapter/tree/master/packages/wallets/walletconnect) was set up a month ago. I would be happy to create a PR but it seems that because it the adapter accepts nonstandard options such as a `projectId` field, it's slightly nontrivial to integrate (happy to take a stab). The use case I have is for fireblocks support.

**Comment by michaelhly** [comment]
We'd be happy to take a PR!

**Comment by iulianbarbu** [comment]
Can an admin trigger the `Release` workflow? Interesting in consuming the wallet-connect support. 

cc: @michaelhly

**Comment by michaelhly** [comment]
@iulianbarbu released!
